### ISSUE TITLE
message's std::string ctor is confusing

### ISSUE THREAD

**Issue by oliora** [zeromq/azmq#113]
`azmq::message` has only a syntax sugar ctor to construct from `std::string`. Any other construction from common "buffer representation" (e.g. c-string, void ptr + size, std::array etc) needs a call of `boost::asio::buffer()`. This is:

* confusing: different "buffer representations" needs different syntax to construct a message from
* non-effective: when user constructs message from c-string, temporary `std::string` is allocated.

I propose either:

1. Remove `std::string` ctor
2. Add syntax sugar ctors for common "buffer representations", at least for the following ones:
  * `const void *` + `size_t`
  * c-string

**Comment by rodgert** [comment]
It is sugar, definitely but not an uncommon usage. I propose
boost::string_ref (std::string_view under '17) as an alternative.

**Comment by oliora** [comment]
Let's add `boost::string_ref` constructor and remove `std::string` one then.

`std::string_view` one may be added later when it became widely available in compilers.

**Comment by rodgert** [comment]
Agreed. I will add it shortly.

**Comment by rodgert** [comment]
I may get a chance to do this today, I have immediate use for it.
