### ISSUE TITLE
Setting detached option on client socket of Actor throws exception

### ISSUE THREAD

**Issue by mschuckmann** [zeromq/azmq#123]
I believe that I will need have the backend thread of an Actor run without calling the service_io::run() method so in following the recommendations from the Actor class documentation I've tried setting the detached option on the client socket like so: 

```
server_t::server_t( asio::io_service & ios, const char* name )
  : pimple_(std::make_shared<impl>(name))
  , frontend_(azmq::actor::spawn(ios, run, pimple_) )
{
  this->frontend_.set_option(azmq::actor::detached(true)); 
}
```

However this causes an exception (errno 22 invalid argument) to be thrown. 
It appears the exception occurs because option gets passed on to the zmq socket after it is handled by ext handler and zmq_setsocketopt() returns a -1. See set_option() in socket_service.hpp, and set_option() in socket_ops.hpp. 

Am I missing something or is this a bug?

**Comment by rodgert** [comment]
Sounds like a legitimate bug. In general if it's handled, it shouldn't pass it on.
