### ISSUE TITLE
boost 1.60 undefined reference

### ISSUE THREAD

**Issue by ahundt** [zeromq/azmq#125]
I tried building azmq on boost 1.60 and ran into an undefined reference in Boost.regex.

build logs here:
https://gist.github.com/1158a864123d02097954bd34b4dcfe0c

**Comment by rodgert** [comment]
brew install icu4c

Maybe?

**Comment by oliora** [comment]
Try to run `brew link --force icu4c` then completely cleanup the workspace dir and run CMake again.

**Comment by rodgert** [comment]
Assuming this is a non-issue and closing

**Comment by ahundt** [comment]
@rodgert yeah hasn't been a problem, thanks!
