### ISSUE TITLE
AZMQ does not receive async callbacks on windows platform

### ISSUE THREAD

**Issue by entd** [zeromq/azmq#126]
No matter what example or whatever I do I cannot receive async on windows with azmq. I am using tcp transport. Blocking receive works.

**Comment by entd** [comment]
Somehow it requires work wrapping around ios. Still some of your examples does not work. But that not as big issue.

**Comment by rodgert** [comment]
Are you referring to io_service::work on io_service instance? The examples
seem to work fine on Linux/OSX without this. I don't have access to a
Windows machine. @oliora?

**Comment by entd** [comment]
Actor one seems to not to receive/send pings and pongs. Also I am having
strange behaviour on scheduling async receive on same thread as io_service
running (via pool) it gets empty messages. I will try to test same thing on
linux and see if I am abusing azmq or this is something wrong with windows
platform.

2016-10-25 21:14 "Thomas Rodgers" <notifications@github.com> rašė:

**Comment by oliora** [comment]
I'll check behavior on Windows, but can't promise any ETA for this.
