### ISSUE TITLE
Add versioning of releases or tags

### ISSUE THREAD

**Issue by drdas** [zeromq/azmq#127]
Is there any plan to add proper versioning? It is difficult to use this in production as we have no idea when it is tested and stable.

**Comment by kgreenek** [comment]
Major +1 for this!

Right now we have to manually try to figure out what commits are stable / tested at random commits on master, and there is no way of knowing when you guys have made API breaking changes, etc.

It would help us out a lot with using azmq in production if you guys start doing proper semantic versioning: http://semver.org/

Thanks!

**Comment by rodgert** [comment]
I will do this over the next week. I expect to follow the forked repo per release model used by ZeroMQ itself. Until that's in place, I won't merge anything else into master on this repo (e.g. this is 1.0).

**Comment by rodgert** [comment]
I've tagged a v1.0 and created a top level stable azmq1-0 repo from that tagged point.

**Comment by kgreenek** [comment]
Thanks!
