### ISSUE TITLE
CPack support

### ISSUE THREAD

**Issue by mbasunov** [zeromq/azmq#137]
That nice to have CPack support for easy packaging and redistribution.

**Comment by rodgert** [comment]
I can investigate what it would take, no guarantees (yet).

**Comment by mbasunov** [comment]
Just look into my commits - all work already done.
Packaging looks simple:
> mkdir build
> cd build
> cmake -DAZMQ_NO_TESTS=1 -DCPACK_PACKAGE_CONTACT=maintainer@example.com ..
> cpack -G RPM
> cpack -G DEB
