### ISSUE TITLE
Compatibility with boost down to 1.48

### ISSUE THREAD

**Issue by mbasunov** [zeromq/azmq#138]
Having AZMQ compatible with earlier Boost versions could be useful for using AZMQ in CentOS 6/7.

**Comment by rodgert** [comment]
I meant the CPack reply for this request. I’ll investigate compatibility
with older versions of Boost to see if supporting CentOS6 is feasible.

**Comment by mbasunov** [comment]
I've never checked against Boost supplied with CentOS 6 because it is too old for me and I'm using Boost 1.48 from EPEL as a replacement.
