### ISSUE TITLE
can't construct azmq socket

### ISSUE THREAD

**Issue by beastplus** [zeromq/azmq#148]
When attempting run the code that used in the README.md example, I get a exception, the error code is ERROR_INVALID_PARAMETER. it's thrown by win_iocp_io_context when call the method CreateIoCompletionPort during create new instance of azmq::sub_socket. if defined BOOST_ASIO_DISABLE_IOCP,it worked fine.
the develop environment is
windows10 x64
visual studio 2017 + vcpkg(triplet x64-windows)
cmake 3.13.2
zmq 4.3.1
azmq 1.0.2
boost 1.68

**Comment by sigiesec** [comment]
See zeromq/libzmq#3269

**Comment by sigiesec** [comment]
I reproduced the issue in libzmq, and will soon submit a PR. Since it is a libzmq issue, this issue can probably be closed.

**Comment by beastplus** [comment]
thank you for reply,i will try later
