### ISSUE TITLE
Issues while building on RHEL7 with boost 1.53 on master

### ISSUE THREAD

**Issue by phubner** [zeromq/azmq#153]
There is an error in the `BOOST_VERSION` check in socket_service which causes the use of `boost::asio::post`. 

Also, `boost::string_ref` in 1.53 is not as mature as 1.54 and causes an error when comparing a string_ref to a char array.

I will provide a pull request to address these issues.

**Comment by phubner** [comment]
Just fyi, i am having an issue creating my pull request. I am used to creating a separate branch that I can push my commits to but seems like I cannot do that.

**Comment by aboseley** [comment]
For the project and create a branch on you fork
