### ISSUE TITLE
possible memory leak in `socket_service::enqueue`

### ISSUE THREAD

**Issue by timblechmann** [zeromq/azmq#165]
running address sanitizer on my application gave me memory leaks of `reactor_op_ptr` from:
https://github.com/zeromq/azmq/blob/master/azmq/detail/socket_service.hpp#L482-L490

where is this memory supposed to be freed? it is a leak inside azmq or is it something that should be handled on the application side?

**Comment by dkl** [comment]
We saw this also – it looks like `per_descriptor_data` should free the remaining objects its `op_queue_` on destruction, but doesn't do so.
