### ISSUE TITLE
Build fails with boost 1.76.0

### ISSUE THREAD

**Issue by bjkaria** [zeromq/azmq#173]
socket.hpp still uses the get_io_service() which was removed in boost 1.70.0. The project no longer builds with the latest boost version.

Using g++ 9.3.0 and boost 1.76.0 on ubuntu 20.04

```
~/src/azmq/detail/socket_service.hpp:546:28: error: ‘class boost::asio::posix::basic_stream_descriptor<>’ has no member named ‘get_io_service’
  546 |                 impl->sd_->get_io_service().post([weak_impl, ec]() { handle_missed_events(weak_impl, ec); });
```

**Comment by aboseley** [comment]
Hey @bjkaria , what git-hash of azmq are you using? 

I've just tried the latest version on master (f4661fe559405bcd) and its compiling OK in Ubuntu 20.04, with boost 1.76

**Comment by bjkaria** [comment]
I confirm that master builds fine. I had v1.0.2 in my cache. Are there plans to apply a release tag?
