### ISSUE TITLE
max_sockets references incorrect ZMQ_MAXMSGSIZE

### ISSUE THREAD

**Issue by jvanns** [zeromq/azmq#190]
This line;
`using max_sockets = opt::integer<ZMQ_MAXMSGSIZE>;`
Should probably be;
`using max_sockets = opt::integer<ZMQ_MAX_SOCKETS>;`
See here;
https://github.com/zeromq/azmq/blob/master/azmq/detail/context_ops.hpp#L31

I needed to increase this for subscribing to >1000 channels/topics and found that it didn't work - because of this bug. Changing it locally and recompiling had the desired effect. Incidentally, I think the project (which is great BTW) would benefit from a few examples on how to properly set context options ;)

**Comment by jvanns** [comment]
Here, I created a pull request; https://github.com/zeromq/azmq/pull/191

**Comment by aboseley** [comment]
change merged
