### ISSUE TITLE
Doesn't build with latest catch2

### ISSUE THREAD

**Issue by keith-dev** [zeromq/azmq#193]
The latest catch2 doesn't have file catch2/catch.hpp.
Replacing that name with catch2/catch_all.hpp results in no main() defined at link time.

**Comment by aboseley** [comment]
It looks like the latest catch2 version breaks the v2 api, and will be eventually released as v3.

**Comment by aboseley** [comment]
@keith-dev , does this fix the issue 
https://github.com/zeromq/azmq/pull/194
