### ISSUE TITLE
Outdated FindAzioMQ.cmake

### ISSUE THREAD

**Issue by oliora** [zeromq/azmq#37]
Current `FindAzioMQ.cmake` has several problems:
- Has outdated name (should be `FindAZMQ.cmake`).
- Provides `AzioMQ_LIBRARIES` although AZMQ is header only now.
- Extracts version in platform dependent way with using of `grep`.
- Doesn't do a version checking.

Because this file is need to be almost rewritten from scratch, I propose not only fix the problems but switch from CMake finder module approach to package config one (see http://www.cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file). New approach is simpler in implementation than existing one and also gives ability to provide a list of dependent libraries for transitive linking.

**Comment by ahundt** [comment]
I second this issue. The find script is completely broken.

**Comment by rodgert** [comment]
I don't really have a way to test this on Windows, but I will try to
improve the find script (*nix-en) this week.

**Comment by ahundt** [comment]
I made a simple one that works for me here:
https://github.com/ahundt/robone/blob/master/config/FindAZMQ.cmake

**Comment by oliora** [comment]
@rodgert I don't have time to write it, but I can test it, when it will be ready. 
@ahundt it looks good. Could you please also update the script description?

**Comment by oliora** [comment]
@ahundt oh, I see it's a file from the project, not a gist. No reason to change it there of course.

**Comment by aboseley** [comment]
FindAzioMQ should replace with a standard config file
