### ISSUE TITLE
CMake somehow fails to find libzmq on Windows 8.1 x64 with VS2013

### ISSUE THREAD

**Issue by toresbe** [zeromq/azmq#57]
Hello! I'm having some odd problems building azmq on Windows. This may be a rookie mistake because I'm not familiar with software development in a Windows environment, but maybe someone might have some useful info on where to go from here.

I have installed [the x64 build](http://miru.hk/archive/ZeroMQ-4.0.4~miru1.0-x64.exe) of libzmq from the [ZeroMQ website](http://zeromq.org/distro:microsoft-windows).

I have tried this with and without -G"Visual Studio 12 Win64".

	...\build>set ZMQ_ROOT=C:\Program Files\ZeroMQ 4.0.4
	...\build>set BOOST_ROOT=C:\Program Files\boost_1_57_0
	...\build>cmake .. -G"Visual Studio 12 Win64"
	-- The C compiler identification is MSVC 18.0.30723.0
	-- The CXX compiler identification is MSVC 18.0.30723.0
	-- Check for working C compiler using: Visual Studio 12 2013 Win64
	-- Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Check for working CXX compiler using: Visual Studio 12 2013 Win64
	-- Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	CMake Warning (dev) at CMakeLists.txt:4 (if):
	  Policy CMP0054 is not set: Only interpret if() arguments as variables or
	  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
	  details.  Use the cmake_policy command to set the policy and suppress this
	  warning.

	  Quoted variables like "MSVC" will no longer be dereferenced when the policy
	  is set to NEW.  Since the policy is not set the OLD behavior will be used.
	This warning is for project developers.  Use -Wno-dev to suppress it.

	-- Boost version: 1.57.0
	-- Found the following Boost libraries:
	--   system
	--   log
	--   unit_test_framework
	--   date_time
	--   thread
	--   chrono
	--   regex
	--   random
	CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
	  Could NOT find ZeroMQ (missing: ZeroMQ_LIBRARIES) (found suitable version
	  "4.0", minimum required is "4.0")
	Call Stack (most recent call first):
	  C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
	  config/FindZeroMQ.cmake:60 (find_package_handle_standard_args)
	  CMakeLists.txt:37 (find_package)

Please let me know if there's any more information that would be useful. I'm idling in Freenode/zeromq as toresbe; please ask if there's anything I can contribute with.

**Comment by toresbe** [comment]
FWIW, this builds just fine as a Visual Studio 2013 project.

**Comment by rodgert** [comment]
I know @oliora was looking at fixing the FindZMQ module for Windows, but I
don't know the status of it.

**Comment by oliora** [comment]
I will take a look. Unfortunately I don't have Windows 8.1 installed

**Comment by oliora** [comment]
Implemented. Can be closed

**Comment by toresbe** [comment]
Confirmed working on Windows 8.1, thanks for the response! :)
