### ISSUE TITLE
Non-Boost Asio

### ISSUE THREAD

**Issue by btolfa** [zeromq/azmq#62]
How difficult it will be to rewrite azmq without boost? http://think-async.com/Asio/AsioStandalone

**Comment by rodgert** [comment]
I haven't seriously considered it. Obviously I could take the route ChrisK
took to mechanically transform sources and that would cover most, but not
all, of the use of Boost in the library. Some of which exists to work
around (still) broken C++11 library implementations and compiler
deficiencies (eg Microsoft).

Also, my projects are all completely dependent on Boost, so it isn't a
priority for me.

What I do want to explore, however, is a version which makes use of the
standards track Asio that is part of the new Networking TS that we voted in
during the fall C++ Standards Committee meeting. This is a longer term plan
as the spec is not yet stable, and still lacks support for one feature that
azmq requires (posix::stream_descriptor).

**Comment by ruipacheco** [comment]
I'm taking a shot at this. I don't want to drag Boost into my project. No clue when it will be done, though.

**Comment by rodgert** [comment]
Patches are definitely welcome. Please note, in some cases we switched from
the C++11 standard types to the Boost types to smooth over issues compiling
on MSVC.  That should be preserved until MSVC2015 is "the norm". The
"right" way to do this would be to make a set of typedefs to cover which
thread/mutex/condition_variable/error_code/etc. types are used based on
some conditional compilation. I may take a stab at that change in the next
week.

By way of advance warning, I am going to be refactoring
detail/socket_service.hpp in the next week or two to clean that up, it is a
fairly intrusive set of changes so there is likely to be some churn
involving that file and the details in socket.hpp (though not the public
surface area of the socket type).

**Comment by ruipacheco** [comment]
I can’t test on Windows unfortunately.

**Comment by rodgert** [comment]
Nor can I. We have a CI build on Pull Requests which covers Windows, @oliora usually catches Windows breakage and weighs in on how to best address it.

One other potential issue - The code for bind() on the socket uses regular expressions, specifically  boost::regex. I know that std::regex was broken on GCC4.7, and probably 4.8, so the minimum GCC compiler requirement is going to be GCC4.9 (I believe libstdc++ is fine from Clang3.4 on).

**Comment by ruipacheco** [comment]
Ok

**Comment by ruipacheco** [comment]
I've done some work as you can see from my fork and I've now hit a problem: 

`./azmq/socket.hpp:108:35: error: use of undeclared identifier 'implementation'; did you mean 'implementation_'?`

What are you trying to do here?

**Comment by rodgert** [comment]
See the documentation for the asio::basic_io_object
<http://www.boost.org/doc/libs/1_57_0/doc/html/boost_asio/reference/basic_io_object.html>
template. This pattern is repeated throughout both Asio and Azmq, and has
to do with the way basic_io_object interfaces with implementations of
asio::io_service::service_base.

**Comment by rodgert** [comment]
I still need to finish the 2nd and 3rd parts of this post (Real Soon Now),
but see http://rodgert.github.io/2014/12/24/boost-asio-and-zeromq-pt1/ for
more information on this structure in Asio and Azmq.

**Comment by oliora** [comment]
Having a Boost-less version is a nice feature.

Although it has some issues:

1. gcc 4.8 has a very limited `std::regex` support (better described as doesn't have it :). Only gcc 4.9 and above completely supports it. So going without Boost will require quite modern compiler.
2. MSVC 2013 has limited support of C++11 features. Things affecting AZMQ are at least: no noexcept, no inline namespaces. This wrapped by Boost, but can be done by AZMQ code itself.
3. Using of `std::thread` and `std::mutex` instead of Boost analogues is more chance to stumble upon [DllMain restrictions](https://msdn.microsoft.com/en-us/library/windows/desktop/dn633971%28v=vs.85%29.aspx) on Windows and come to a deadlock during startup or shutdown, so using of Boost threading is preferable if available. So we definitely will need two set of typedefs for threading classes.

**Comment by ruipacheco** [comment]
I'd like to keep my branch as C++11 as possible. Maybe we don't merge 
until there is compiler support, meanwhile keeping a reference to my 
fork on the README file?

On 18/03/15 16:56, Andrey Upadyshev wrote:
>
> Having a Boost-less version is a nice feature.
>
> Although it has some issues:
>
>  1. gcc 4.8 has a very limited |std::regex| support (better described
>     as doesn't have it :). Only gcc 4.9 and above completely supports
>     it. So going without Boost will require quite modern compiler.
>  2. MSVC 2013 has limited support of C++11 features. Things affecting
>     AZMQ are at least: no noexcept, no inline namespaces. This wrapped
>     by Boost, but can be done by AZMQ code itself.
>  3. Using of |std::thread| and |std::mutex| instead of Boost analogues
>     is more chance to stumble upon DllMain restrictions
>     <https://msdn.microsoft.com/en-us/library/windows/desktop/dn633971%28v=vs.85%29.aspx>
>     on Windows and come to a deadlock during startup or shutdown, so
>     using of Boost threading is preferable if available. So we
>     definitely will need two set of typedefs for threading classes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/zeromq/azmq/issues/62#issuecomment-83033118>.
>

-- 
--
Rui Pacheco

**Comment by rodgert** [comment]
Azmq expects C++11 as the minimum compiler requirement and makes extensive
use of C++11 only features already. The issue then is only how we support
common 'pre-standard' compilers which lack full standards coverage.
Compilers tend to have a fairly long tail (I expect to be encountering
GCC4.8, for instance, for at least another 18-36 months) so maintaining a
fork may be less than pleasant prospect.

I think it is possible to configure, by proper typedefs and macros,
something that can deal with older compilers currently supported without
the need to maintain a fork.

I intend to take an initial stab at this in the next week.

**Comment by oliora** [comment]
Guys,
I can put boost-free branch under CI and port it on Windows

**Comment by ruipacheco** [comment]
I won’t be able to get any work done until next weekend unfortunately.

But I need this so it will be done.

**Comment by rodgert** [comment]
I have a pending pull request that introduces azmq/detail/config.hpp and azmq/detail/config/* to start collecting platform/compiler specific conditional defines, typedefs, etc. My plan is to move slowly toward consuming definitions for things like thread/mutex/etc. from this tree. I think this should also extend to type aliases for Asio types (and system_error/errc) to switch between boost/non-boost Asio.

@oliora For non MSVC targets, I am going to start introducing #defines in config.hpp to select std::thread/std::mutex in preference over their boost equivalents.

**Comment by ruipacheco** [comment]
I'm moving slowly. I do some work every week but its not as fast as I want.

**Comment by ruipacheco** [comment]
As I said, this is moving slowly.

A question: would you have a problem if with me using [clang-format](http://clang.llvm.org/docs/ClangFormat.html) on the source? This would probably ruin the diff so it's something to think about.

Also, this question does not imply that the project is near completion.

**Comment by rodgert** [comment]
I got a demo of the tool a year ago from the Clang devs at a C++ committee
meeting. I think it is an interesting tool, and perhaps worth pursuing,
but I want any source-wide wholesale reformat being part of a change that
*only* applies a pre-agreed upon style. Such a change would also involve
updating the contribution notes indicating the style.

Which style do you prefer?

**Comment by ruipacheco** [comment]
I like Google’s C++ style as it saves a lot of space -  C++ is pretty verbose.

I already have a .clang-format file that I use in another project. It’s just a question of copying it here and running the tool as needed.

If you prefer another style we can either try to make clang-format adhere to it or just ignore clang-format completely.

**Comment by rodgert** [comment]
Ok, I'd say hold off for now, and let me play around a bit with it. I tend
to prefer liberal use of white space, and I don't really like very 'dense'
code. I have found this to be a maintenance headache in other projects.

**Comment by ruipacheco** [comment]
Of course, go for it.

**Comment by rodgert** [comment]
It seems that the LLVM style + 4-space indent would be closest to what is currently used. I am going to muck about with this as a starting point.

**Comment by ruipacheco** [comment]
Ok, that’s cool. If you create a clang-format file send it to me. I don’t want to pull from your repo and diff the formatting.

**Comment by rodgert** [comment]
If I get something I'm happy with, I may do a bulk reformat according to that style (heads up before doing so obviously). If you reformatted according to the same style file, it should make any subsequent diffs easy (well as easy as such things ever are).

I have some additional commits related to stand alone Asio support that I want to merge upstream first in any event.

**Comment by ruipacheco** [comment]
Ok. What are they?

**Comment by rodgert** [comment]
in general, slowly replacing anything in Boost (except Asio as of yet) with their standard library equivalents. Specifically, the most recent changes are in 

https://github.com/rodgert/azmq/tree/master/azmq/detail/config.hpp
https://github.com/rodgert/azmq/tree/master/azmq/detail/config/

As I encounter boost-isms that are easily switched out, I am populating this directory and adjusting config.hpp as appropriate, but it is a work in progress. There are also some dependencies on boost flat_map and boost intrusive list that I am working on, along with propagating changes related to the definitions already in config.hpp & config/ but I don't anticipate landing those changes before the weekend.

**Comment by ruipacheco** [comment]
Check my fork, that’s exactly what I’m doing and I have a ton of work done.

**Comment by ruipacheco** [comment]
May I ask you to take a look at boost::match_partial? The lack of an std:: equivalent is the only thing keeping me from yanking boost::reggae out.

**Comment by rodgert** [comment]
boost::reggae :)

Yes, I will have a look.

**Comment by ruipacheco** [comment]
Betrayed by auto-complete. And please do tell me what you think of my commits so far.

It’s a bit silly to have two people do the same work.

**Comment by rodgert** [comment]
I took a brief look at your fork (I will try to spend more time this
evening), but the biggest difference I see is that it looks like you are
out right preferring the C++11 version to the boost version of a type (e.g.
std::thread vs. boost::thread).

While this is ideal, and in fact my original version was exactly this, it
is not quite practical because the code needs to support a version of the
Microsoft compiler in which there are problems with some of the C++11
constructs. As @oliora worked on porting to MSVC, we switched to the Boost
equivalents to paper over deficiencies in that compiler. I think, in order
to end up with a consistent code base that can target standalone Asio AND
the existing targets these choices need to be configurable at compile time,
which is where I am headed with the whole config.hpp, config/*.hpp
structure.

**Comment by ruipacheco** [comment]
I don't think we have much of a choice, given that the problem lies with 
a compiler or family of compilers.

I guess I should stop what I'm doing and give you any backup you need?

On 14/04/15 16:30, Thomas Rodgers wrote:
> I took a brief look at your fork (I will try to spend more time this
> evening), but the biggest difference I see is that it looks like you are
> out right preferring the C++11 version to the boost version of a type 
> (e.g.
> std::thread vs. boost::thread).
>
> While this is ideal, and in fact my original version was exactly this, it
> is not quite practical because the code needs to support a version of the
> Microsoft compiler in which there are problems with some of the C++11
> constructs. As @oliora worked on porting to MSVC, we switched to the Boost
> equivalents to paper over deficiencies in that compiler. I think, in order
> to end up with a consistent code base that can target standalone Asio AND
> the existing targets these choices need to be configurable at compile 
> time,
> which is where I am headed with the whole config.hpp, config/*.hpp
> structure.
>
> On Mon, Apr 13, 2015 at 3:36 PM, Rui Pacheco <notifications@github.com>
> wrote:
>
> > Betrayed by auto-complete. And please do tell me what you think of my
> > commits so far.
> >
> > It’s a bit silly to have two people do the same work.
> >
> > > On 13 Apr 2015, at 22:34, Thomas Rodgers <notifications@github.com>
> > wrote:
> > >
> > > boost::reggae :)
> > >
> > > Yes, I will have a look.
> > >
> > > On Monday, April 13, 2015, Rui Pacheco <notifications@github.com> 
> wrote:
> > >
> > > > May I ask you to take a look at boost::match_partial? The lack of an
> > std::
> > > > equivalent is the only thing keeping me from yanking 
> boost::reggae out.
> > > >
> > > > > On 13 Apr 2015, at 22:05, Thomas Rodgers <notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > > >
> > > > > in general, slowly replacing anything in Boost (except Asio as of
> > yet)
> > > > with their standard library equivalents. Specifically, the most 
> recent
> > > > changes are in
> > > > >
> > > > > 
> https://github.com/rodgert/azmq/tree/master/azmq/detail/config.hpp <
> > > > https://github.com/rodgert/azmq/tree/master/azmq/detail/config.hpp>
> > > > > https://github.com/rodgert/azmq/tree/master/azmq/detail/config/ <
> > > > https://github.com/rodgert/azmq/tree/master/azmq/detail/config/>
> > > > > As I encounter boost-isms that are easily switched out, I am
> > populating
> > > > this directory and adjusting config.hpp as appropriate, but it is a
> > work in
> > > > progress. There are also some dependencies on boost flat_map and 
> boost
> > > > intrusive list that I am working on, along with propagating changes
> > related
> > > > to the definitions already in config.hpp & config/ but I don't
> > anticipate
> > > > landing those changes before the weekend.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub <
> > > > https://github.com/zeromq/azmq/issues/62#issuecomment-92481991>.
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/zeromq/azmq/issues/62#issuecomment-92482608>.
> > > >
> > > —
> > > Reply to this email directly or view it on GitHub <
> > https://github.com/zeromq/azmq/issues/62#issuecomment-92490479>.
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/zeromq/azmq/issues/62#issuecomment-92491011>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/zeromq/azmq/issues/62#issuecomment-92876728>.
>

-- 
Rui Pacheco

**Comment by rodgert** [comment]
Perhaps, my interest level in doing this work has gone up since I
originally claimed it wasn't something I had a pressing need for. I would
like to prefer the standard library over Boost where there is functional
parity in any event, and I think that covers the majority of the required
changes in any event.

I have some actor related work and a refactoring of socket_service that
have been slowly moving along in varying stages of completion. I am happy
to shelve them for a few weeks and just pound this out. If you are
interested in collaborating around my personal fork?

**Comment by ruipacheco** [comment]
Very much. I suggest you parcel out specific tasks and I’ll do them. You know the library better than me and I’m sure you’re a way better C++ programmer than I am.

**Comment by rodgert** [comment]
@oliora was also interested, I think, in parcelling out and making these
changes (plus, he has the most experience with the MSFT compiler issues).
Let me try to organize a punch list over the next couple of days and we can
start from there.

**Comment by oliora** [comment]
@ruipacheco please check this discussion to be more on the same page: https://github.com/zeromq/azmq/pull/71#discussion-diff-27663189

**Comment by ruipacheco** [comment]
Cool!

On 14/04/15 21:12, Thomas Rodgers wrote:
> @oliora was also interested, I think, in parcelling out and making these
> changes (plus, he has the most experience with the MSFT compiler issues).
> Let me try to organize a punch list over the next couple of days and 
> we can
> start from there.
>
> On Tue, Apr 14, 2015 at 11:44 AM, Rui Pacheco <notifications@github.com>
> wrote:
>
> > Very much. I suggest you parcel out specific tasks and I’ll do them. You
> > know the library better than me and I’m sure you’re a way better C++
> > programmer than I am.
> >
> >
> > > On 14 Apr 2015, at 17:04, Thomas Rodgers <notifications@github.com>
> > wrote:
> > >
> > > Perhaps, my interest level in doing this work has gone up since I
> > > originally claimed it wasn't something I had a pressing need for. 
> I would
> > > like to prefer the standard library over Boost where there is 
> functional
> > > parity in any event, and I think that covers the majority of the 
> required
> > > changes in any event.
> > >
> > > I have some actor related work and a refactoring of socket_service 
> that
> > > have been slowly moving along in varying stages of completion. I 
> am happy
> > > to shelve them for a few weeks and just pound this out. If you are
> > > interested in collaborating around my personal fork?
> > >
> > > On Tue, Apr 14, 2015 at 9:33 AM, Rui Pacheco 
> <notifications@github.com>
> > > wrote:
> > >
> > > > I don't think we have much of a choice, given that the problem lies
> > with
> > > > a compiler or family of compilers.
> > > >
> > > > I guess I should stop what I'm doing and give you any backup you 
> need?
> > > >
> > > >
> > > > On 14/04/15 16:30, Thomas Rodgers wrote:
> > > > > I took a brief look at your fork (I will try to spend more 
> time this
> > > > > evening), but the biggest difference I see is that it looks 
> like you
> > are
> > > > > out right preferring the C++11 version to the boost version of 
> a type
> > > > > (e.g.
> > > > > std::thread vs. boost::thread).
> > > > >
> > > > > While this is ideal, and in fact my original version was exactly
> > this, it
> > > > > is not quite practical because the code needs to support a version
> > of the
> > > > > Microsoft compiler in which there are problems with some of 
> the C++11
> > > > > constructs. As @oliora worked on porting to MSVC, we switched 
> to the
> > > > Boost
> > > > > equivalents to paper over deficiencies in that compiler. I 
> think, in
> > > > order
> > > > > to end up with a consistent code base that can target standalone
> > Asio AND
> > > > > the existing targets these choices need to be configurable at 
> compile
> > > > > time,
> > > > > which is where I am headed with the whole config.hpp, config/*.hpp
> > > > > structure.
> > > > >
> > > > > On Mon, Apr 13, 2015 at 3:36 PM, Rui Pacheco <
> > notifications@github.com>
> > > > > wrote:
> > > > >
> > > > > > Betrayed by auto-complete. And please do tell me what you 
> think of
> > my
> > > > > > commits so far.
> > > > > >
> > > > > > It’s a bit silly to have two people do the same work.
> > > > > >
> > > > > > > On 13 Apr 2015, at 22:34, Thomas Rodgers <
> > notifications@github.com>
> > > > > > wrote:
> > > > > > >
> > > > > > > boost::reggae :)
> > > > > > >
> > > > > > > Yes, I will have a look.
> > > > > > >
> > > > > > > On Monday, April 13, 2015, Rui Pacheco 
> <notifications@github.com
> > >
> > > > > wrote:
> > > > > > >
> > > > > > > > May I ask you to take a look at boost::match_partial? 
> The lack
> > of
> > > > an
> > > > > > std::
> > > > > > > > equivalent is the only thing keeping me from yanking
> > > > > boost::reggae out.
> > > > > > > >
> > > > > > > > > On 13 Apr 2015, at 22:05, Thomas Rodgers <
> > > > notifications@github.com
> > > > > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > > > > > > > >
> > > > > > > > > in general, slowly replacing anything in Boost (except 
> Asio
> > as of
> > > > > > yet)
> > > > > > > > with their standard library equivalents. Specifically, 
> the most
> > > > > recent
> > > > > > > > changes are in
> > > > > > > > >
> > > > > > > > >
> > > > > 
> https://github.com/rodgert/azmq/tree/master/azmq/detail/config.hpp <
> > > > > > > >
> > https://github.com/rodgert/azmq/tree/master/azmq/detail/config.hpp
> > > > >
> > > > > > > > >
> > https://github.com/rodgert/azmq/tree/master/azmq/detail/config/
> > > > <
> > > > > > > >
> > https://github.com/rodgert/azmq/tree/master/azmq/detail/config/>
> > > > > > > > > As I encounter boost-isms that are easily switched 
> out, I am
> > > > > > populating
> > > > > > > > this directory and adjusting config.hpp as appropriate, 
> but it
> > is a
> > > > > > work in
> > > > > > > > progress. There are also some dependencies on boost flat_map
> > and
> > > > > boost
> > > > > > > > intrusive list that I am working on, along with propagating
> > changes
> > > > > > related
> > > > > > > > to the definitions already in config.hpp & config/ but I 
> don't
> > > > > > anticipate
> > > > > > > > landing those changes before the weekend.
> > > > > > > > >
> > > > > > > > > —
> > > > > > > > > Reply to this email directly or view it on GitHub <
> > > > > > > > 
> https://github.com/zeromq/azmq/issues/62#issuecomment-92481991
> > >.
> > > > > > > > >
> > > > > > > >
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > <
> > https://github.com/zeromq/azmq/issues/62#issuecomment-92482608>.
> > > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub <
> > > > > > https://github.com/zeromq/azmq/issues/62#issuecomment-92490479>.
> > > > > >
> > > > > > >
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > 
> <https://github.com/zeromq/azmq/issues/62#issuecomment-92491011>.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/zeromq/azmq/issues/62#issuecomment-92876728>.
> > > > >
> > > >
> > > > --
> > > > Rui Pacheco
> > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/zeromq/azmq/issues/62#issuecomment-92878912>.
> > > >
> > > —
> > > Reply to this email directly or view it on GitHub <
> > https://github.com/zeromq/azmq/issues/62#issuecomment-92894144>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/zeromq/azmq/issues/62#issuecomment-92971574>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/zeromq/azmq/issues/62#issuecomment-93024134>.
>

-- 
Rui Pacheco

**Comment by ruipacheco** [comment]
I'm going to stop working on this for the time being. I've come across some [issues](https://www.reddit.com/r/programming/comments/3349p7/a_look_at_nanomsg_and_scalability_protocols_why/cqhk13h) with ZeroMQ that made me want to look at nanomsg a bit closer and possibly replicate this project for nanomsg.

**Comment by hintjens** [comment]
Not that I ever hit this issue, but if edge triggering was such an issue,
surely someone would have tried to change it in libzmq by now?

**Comment by rodgert** [comment]
Ok, I will likely complete it in any event over the next couple of weeks

**Comment by ruipacheco** [comment]
Maybe the issue is too complex? I mean, nanomsg was created due to lessos learned with 0mq.

**Comment by hintjens** [comment]
Lessons are relative. ZeroMQ is not a library, it's a community. This is
the only significant difference afaics.

**Comment by rodgert** [comment]
'maybe the issue is too complex' -

There is some complexity in supporting a broad range of compilers at
varying levels of standards compliance. That is not a 'lesson learned' from
ZeroMQ or anything particularly relevant to a merits discussion between zmq
and nanomsg, but rather the sad facts of life as a C++ developer.

I built this library to cover my needs, which don't include nanomsg. They
also don't really include standalone Asio, but IMO that is not particularly
complicated.

Also, ZeroMQ has more traction AFAICT and a more 'vibrant' community, which
I value over 'ooh shiny new'.

**Comment by ruipacheco** [comment]
I'm just talking about edge triggering over level triggering. Given the 
fact that nanomsg already handles that for me and it's compatible with 
0mq, why not use it? The best code is the code you don't write, remember?

On 20/04/15 13:31, Thomas Rodgers wrote:
> 'maybe the issue is too complex' -
>
> There is some complexity in supporting a broad range of compilers at
> varying levels of standards compliance. That is not a 'lesson learned' 
> from
> ZeroMQ or anything particularly relevant to a merits discussion 
> between zmq
> and nanomsg, but rather the sad facts of life as a C++ developer.
>
> I built this library to cover my needs, which don't include nanomsg. They
> also don't really include standalone Asio, but IMO that is not 
> particularly
> complicated.
>
> Also, ZeroMQ has more traction AFAICT and a more 'vibrant' community, 
> which
> I value over 'ooh shiny new'.
>
> On Sunday, April 19, 2015, Rui Pacheco <notifications@github.com> wrote:
>
> > Maybe the issue is too complex? I mean, nanomsg was created due to 
> lessos
> > learned with 0mq.
> >
> > Sent from my iPhone
> >
> > > On 19 Apr 2015, at 23:09, Pieter Hintjens <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > >
> > > Not that I ever hit this issue, but if edge triggering was such an 
> issue,
> > > surely someone would have tried to change it in libzmq by now?
> > >
> > > On Sun, Apr 19, 2015 at 9:43 PM, Rui Pacheco <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > wrote:
> > >
> > > > I'm going to stop working on this for the time being. I've come 
> across
> > > > some issues
> > > > <
> > 
> https://www.reddit.com/r/programming/comments/3349p7/a_look_at_nanomsg_and_scalability_protocols_why/cqhk13h
> > >
> > > > with ZeroMQ that made me want to look at nanomsg a bit closer and
> > possibly
> > > > replicate this project for nanomsg.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/zeromq/azmq/issues/62#issuecomment-94307931>.
> > > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/zeromq/azmq/issues/62#issuecomment-94353236>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/zeromq/azmq/issues/62#issuecomment-94428747>.
>

-- 
Rui Pacheco

**Comment by hintjens** [comment]
Nano isn't compatible with ZeroMQ, in any real sense. Different protocols,
different APIs, and different process. Anyhow it's kind of nonsensical to
be discussing this in a thread on a C++ binding to CZMQ, as neither of
these projects have the slightest relevance to Nano.

**Comment by rodgert** [comment]
The problem I had was integration of internal control messaging with UDP
and TCP protocol handlers I don't have control of. I write the latter
(usually) with Asio. nanomsg doesn't do anything for me in that scenario that
isn't already covered by what I have already written.

**Comment by rodgert** [comment]
Minor clarification, azmq binds to libzmq, and incorporates CZMQ behavior
as time, interest and appropreness permit.

But the point (as usual) is spot on.

**Comment by hintjens** [comment]
Ah, sorry. Yes, of course azmq doesn't call CZMQ, my bad.

**Comment by oliora** [comment]
After all, looks like the level triggering is emulated in AZMQ to fix #81. So it should not be an issue any more :)

**Comment by ruipacheco** [comment]
Heard it loud and clear. Didn’t go far with the nanomsg cover because of the day job too :)

> On 23 Jun 2015, at 15:48, Andrey Upadyshev <notifications@github.com> wrote:
> 
> After all, looks like the level triggering is emulated in AZMQ to fix #81 <https://github.com/zeromq/azmq/issues/81>. So it should not be an issue any more :)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/zeromq/azmq/issues/62#issuecomment-114511457>.
> 

--
Rui Pacheco
rui.pacheco@gmail.com
