### ISSUE TITLE
small example of send and receive over loopback not working

### ISSUE THREAD

**Issue by ahundt** [zeromq/azmq#63]
I tried to create a small example, based off the provided example which sends and receives over the loopback interface, but it doesn't seem to receive anything and blocks on that call. I've included a link to the example source below.

https://github.com/ahundt/robone/blob/02e8b28354ef9921304239e38b0626b943a6fd66/src/robone.cpp

Any help would be very much appreciated!

**Comment by rodgert** [comment]
This is not a "bug" per-se, in azmq but a "feature" of the asynchronous nature of libzmq. I added a minimal test - 

https://github.com/rodgert/azmq/blob/master/test/socket/main.cpp starting at line 497.

bind and connect occur asynchronously within libzmq (there is a separate IO thread managed by the zeromq context). 

If you issue bind/connect/send/receive in rapid succession, it is possible that the message you published gets missed because the receiving side is not yet ready. It is not perfect, but inserting a short delay before sending/receiving lets everything get set up correctly.

**Comment by ahundt** [comment]
Thanks for the example! Based on that, I have two additional quick questions. 

Why doesn't the receiver need to specify that it is subscribed to "FOO" since the publisher specified it is sending on that channel?

Also, in https://github.com/rodgert/azmq/blob/master/test/socket/main.cpp#L148 there is an async_receive with a lambda function that is only called once. Is there an easy way to do the same thing but every time data is received initialize another receive call at the end of the function?

Sorry if these are beginner questions, but thanks again for your help!

**Comment by rodgert** [comment]
Not sure I quite follow the first question. It is the SUB socket that sets one or more subscription filters which match against the first n bytes of the published message.

For the second part, this is a pretty common idiom in Asio, but looking at the [examples](http://www.boost.org/doc/libs/1_57_0/doc/html/boost_asio/examples.html) now, I don't see a particularly concise one to point you to. I will add an example (adding examples has been on my todo list for a while now) and link to it shortly.

**Comment by rodgert** [comment]
Have a look at https://github.com/rodgert/azmq/blob/master/doc/examples/actor/main.cpp

This shows a few examples of rescheduling asynchronous operations with both Asio and Azmq, as well an approach to managing state associated with asynchronous operations in Asio.

Questions about what needs clarification definitely welcome.

**Comment by ahundt** [comment]
Oh ok, I was imagining it to work a bit like ROS topics.

http://wiki.ros.org/Topics
http://wiki.ros.org/rostopic
 
I'm not sure I 100% get how the ZMQ version works yet, I'll need to read some more.

**Comment by ahundt** [comment]
Thanks again for the feedback, I ended up being able to get a dealer-dealer connection to work for my use case.
