### ISSUE TITLE
Crash on high rate send

### ISSUE THREAD

**Issue by ahundt** [zeromq/azmq#68]
I created a test that rapidly sends messages on the loopback interface. This test crashes unless I add a 1ms delay between messages. I tried several situations:

| test | result |
| --- | --- |
| two sockets one sending the other receiving, 1ms delay | ok |
| one socket both sending an receiving, 1ms delay | ok |
| 1ms delay between each send | ok |
| no delay between sends | crash |
| 1ms delay for first 5 sends then no delay thereafter | crash |

The messages I am sending are fairly small, around 48 bytes. This is definitely a problem in either AZMQ or ZMQ, because I've implemented pure asio async socket interfaces in the past without encountering these issues. 
## Key Info

[sleep line in main](https://github.com/ahundt/robone/blob/develop/src/AzmqFlatbufferTest.cpp#L53)
[key header implementing send and receive](https://github.com/ahundt/robone/blob/develop/include/robone/AzmqFlatbuffer.hpp)
[gist containing stack trace](https://gist.github.com/ahundt/97c7af569718de837c05)

**Comment by rodgert** [comment]
It is hard to infer anything from the stack traces you referenced. If you have the ability to rebuild with GCC and run under GDB, with 'catch throw' before starting, that might help.

I modified the actor example (using inproc PAIR sockets) to send with both a 1 microsecond delay between sending, and simply posting schedule_ping() back to the io_service (no delay, as fast as it can), I get no crash.

Which version of libzmq are you running with?

I will put together a minimal loopback test tomorrow.

**Comment by rodgert** [comment]
I am unable to reproduce this, see -

https://github.com/zeromq/azmq/pull/69

**Comment by rodgert** [comment]
I have also no tried this on OSX as well, not able to reproduce. If you can get a minimal standalone test case that reproduces the behavior I will look into it further.

Thanks.

**Comment by oliora** [comment]
@ahundt could you try your scenario with the latest version of AZMQ?

**Comment by ahundt** [comment]
Just tried it, commented [the sleep call](https://github.com/ahundt/robone/blob/develop/src/AzmqFlatbufferTest.cpp#L56) then ran the test app. It still seems to crash. If I leave it uncommented it runs without crashing.

Minor side note, with the sleeps it seems to only receive 998 of the 1000 messages and misses the last two, but that doesn't really affect my use case since it is constant streaming of realtime data.

Stack trace
---------------

```
#0	0x00007fff943c01b0 in _platform_memmove$VARIANT$Unknown ()
#1	0x00000001000638fb in boost::asio::buffer_copy(boost::asio::mutable_buffer const&, boost::asio::const_buffer const&) at /usr/local/include/boost/asio/buffer.hpp:1303
#2	0x0000000100063878 in boost::asio::buffer_copy(boost::asio::mutable_buffers_1 const&, boost::asio::const_buffer const&) at /usr/local/include/boost/asio/buffer.hpp:1446
#3	0x0000000100063519 in azmq::message::rebuild(boost::asio::const_buffer const&) at /usr/local/include/azmq/message.hpp:176
#4	0x0000000100063257 in boost::enable_if<boost::has_range_const_iterator<boost::asio::mutable_buffers_1>, unsigned long>::type azmq::detail::socket_ops::send<boost::asio::mutable_buffers_1>(boost::asio::mutable_buffers_1 const&, std::__1::unique_ptr<void, azmq::detail::socket_ops::socket_close>&, int, boost::system::error_code&) at /usr/local/include/azmq/detail/socket_ops.hpp:270
#5	0x0000000100062fbd in azmq::detail::send_buffer_op_base<boost::asio::mutable_buffers_1>::do_perform(azmq::detail::reactor_op*, std::__1::unique_ptr<void, azmq::detail::socket_ops::socket_close>&) at /usr/local/include/azmq/detail/send_op.hpp:38
#6	0x000000010005c86c in azmq::detail::reactor_op::do_perform(std::__1::unique_ptr<void, azmq::detail::socket_ops::socket_close>&) at /usr/local/include/azmq/detail/reactor_op.hpp:29
#7	0x000000010005dc4c in azmq::detail::socket_service::per_descriptor_data::perform_ops(boost::intrusive::list<azmq::detail::reactor_op, boost::intrusive::member_hook<azmq::detail::reactor_op, boost::intrusive::list_member_hook<void, void, void>, &(azmq::detail::reactor_op::member_hook_)>, void, void, void>&, boost::system::error_code&) at /usr/local/include/azmq/detail/socket_service.hpp:118
#8	0x000000010005da24 in azmq::detail::socket_service::handle_missed_events(std::__1::weak_ptr<azmq::detail::socket_service::per_descriptor_data> const&, boost::system::error_code) at /usr/local/include/azmq/detail/socket_service.hpp:520
#9	0x000000010005d94c in azmq::detail::socket_service::check_missed_events(std::__1::shared_ptr<azmq::detail::socket_service::per_descriptor_data>&)::'lambda'()::operator()() const at /usr/local/include/azmq/detail/socket_service.hpp:540
#10	0x000000010005d909 in void boost::asio::asio_handler_invoke<azmq::detail::socket_service::check_missed_events(std::__1::shared_ptr<azmq::detail::socket_service::per_descriptor_data>&)::'lambda'()>(azmq::detail::socket_service::check_missed_events(std::__1::shared_ptr<azmq::detail::socket_service::per_descriptor_data>&)::'lambda'()&, ...) at /usr/local/include/boost/asio/handler_invoke_hook.hpp:69
#11	0x000000010005d7d7 in void boost_asio_handler_invoke_helpers::invoke<azmq::detail::socket_service::check_missed_events(std::__1::shared_ptr<azmq::detail::socket_service::per_descriptor_data>&)::'lambda'(), azmq::detail::socket_service::check_missed_events(std::__1::shared_ptr<azmq::detail::socket_service::per_descriptor_data>&)::'lambda'()>(azmq::detail::socket_service::check_missed_events(std::__1::shared_ptr<azmq::detail::socket_service::per_descriptor_data>&)::'lambda'()&, azmq::detail::socket_service::check_missed_events(std::__1::shared_ptr<azmq::detail::socket_service::per_descriptor_data>&)::'lambda'()&) at /usr/local/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#12	0x000000010005d687 in boost::asio::detail::completion_handler<azmq::detail::socket_service::check_missed_events(std::__1::shared_ptr<azmq::detail::socket_service::per_descriptor_data>&)::'lambda'()>::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) at /usr/local/include/boost/asio/detail/completion_handler.hpp:68
#13	0x00000001000171e7 in boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task_io_service&, boost::system::error_code const&, unsigned long) at /usr/local/include/boost/asio/detail/task_io_service_operation.hpp:38
#14	0x00000001000263d6 in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) at /usr/local/include/boost/asio/detail/impl/task_io_service.ipp:372
#15	0x0000000100025ffd in boost::asio::detail::task_io_service::run(boost::system::error_code&) at /usr/local/include/boost/asio/detail/impl/task_io_service.ipp:149
#16	0x0000000100009701 in boost::asio::io_service::run() at /usr/local/include/boost/asio/impl/io_service.ipp:59
#17	0x0000000100006bec in main at /Users/athundt/source/robonetracker/modules/grl/test/AzmqFlatbufferTest.cpp:137
#18	0x00007fff8f2055c9 in start ()
#19	0x00007fff8f2055c9 in start ()
```

Current ZMQ version
----------------------------
```
± brew info zmq
zeromq: stable 4.0.5 (bottled), HEAD
High-performance, asynchronous messaging library
http://www.zeromq.org/
/usr/local/Cellar/zeromq/4.0.5_2 (64 files, 2.8M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/zeromq.rb
==> Dependencies
Build: pkg-config ✔
Optional: libpgm ✘, libsodium ✘
==> Options
```

**Comment by ahundt** [comment]
I did a minor simplification of the CPP file so now it only relies on AZMQ, ZMQ, Flatbuffers, and Boost.

https://gist.github.com/ahundt/97c7af569718de837c05#file-azmqflatbuffertest_simplified-cpp

**Comment by ahundt** [comment]
I've made an extremely simple example that can reproduce the errors with azmq only:

[Test Cpp](https://gist.github.com/ahundt/97c7af569718de837c05#file-azmqtest-cpp)
[Console Output](https://gist.github.com/ahundt/97c7af569718de837c05#file-azmqtest_consoleoutput-txt)
[Stack Trace](https://gist.github.com/ahundt/97c7af569718de837c05#file-azmqtest_stack_trace-txt)

**Comment by rodgert** [comment]
Am I reading this correctly, you are passing the *same* socket instance
(bind and connect) to bounce?

**Comment by ahundt** [comment]
yes, but last time I checked the same problem occurred when they were different. Could check that again. Can different sockets even bind to the same port?
