### ISSUE TITLE
Wrong error code for operation canceled

### ISSUE THREAD

**Issue by oliora** [zeromq/azmq#75]
To indicate that async operation was cancelled, ASIO uses `boost::asio::error::operation_aborted` while AZMQ uses `boost::system::errc::operation_canceled`. Mentioned errors are the same on Linux (POSIX to be precise), but different on Windows. This is error-prone, so AZMQ should use `boost::asio::error::operation_aborted` too.

**Comment by rodgert** [comment]
Agreed, want to make a PR?

**Comment by oliora** [comment]
Yep. I will do it later today.

**Comment by oliora** [comment]
Fixed
