### ISSUE TITLE
receive MutableBufferSequence ought to return each received buffer size

### ISSUE THREAD

**Issue by nickolasrossi** [zeromq/azmq#79]
I could be missing something, but if I use receive/async_receive with a MutableBufferSequence to read variable-sized multipart messages, nothing is returned that tells me the size of each buffer or the number of parts received. The callback returns total bytes received, but that's not enough to determine part sizes.

To address this I went through an added a "MutableSizes" template parameter to receive_buffer_op and receive_more_buffer_op, set sizes in receive(MutableBufferSequence) and returned number of parts. I can submit a pull request if this is useful, or is there a more elegant way to accomplish this?

**Comment by rodgert** [comment]
This is correct and a function of following how Asio works which maybe isn't a good fit for multipart messages (this would not be the first instance of such an impedance mismatch).

Can you post a link to the commit for these changes so I can review/think about them?

**Comment by nickolasrossi** [comment]
I was about to - then realized I could simply async_receive() each part into an azmq::message_vector (instance kept in a wrapper class) and when all parts are received, pass the vector on to my "real" message handler. You have a synchronous receive_more() function that does this, so perhaps the library could use an async version.

The MutableBufferSequence stuff may get closer to zero-copy though, which might be useful. I'll post those changes for consideration.

**Comment by Jie-Cheng** [comment]
@rodgert @nickolasrossi 
I am having the same issue. Could you please post a code snippet to show how you figured out the sizes of each part? I couldn't figure it out.
