### ISSUE TITLE
100% CPU load in idle mode when router_socket (ZMQ_ROUTER) is used

### ISSUE THREAD

**Issue by oliora** [zeromq/azmq#81]
Using of `router_socket` (`ZMQ_ROUTER` socket type in terms of ZeroMQ) causes 100% load of one CPU core doing nothing. The problem occurs on Linux, OSX and Windows platforms.

The simplest code to reproduce the issue:

```cpp
#include <boost/asio.hpp>
#include <azmq/socket.hpp>

int main()
{
    boost::asio::io_service ios;

    azmq::router_socket s(ios);
    s.bind("tcp://127.0.0.1:9876");

    s.async_receive([](const boost::system::error_code & ec, azmq::message & msg, size_t bytes_transferred) {
    });

    ios.run();

    return 0;
}
```

That's it: no client need to be connected, no actual actions need to be done.

ZeroMQ version 4.0.5 is used.

**Comment by rodgert** [comment]
There is nothing unique to router sockets in azmq vs other socket types. I
vaguely recall an issue from the libzmq list reporting similar behavior, I
will investigate.

**Comment by oliora** [comment]
@rodgert I'll try to reproduce the issue with pure ZMQ. If I can, I'll create a request for them.

**Comment by rodgert** [comment]
Should be informative either way ;->

**Comment by oliora** [comment]
I found a difference in router and dealer sockets which causes AZMQ to call `azmq::detail::socket_service::reactor_handler::schedule()` infinitely: `zmq_getsockopt(ZMQ_EVENTS)` returns `POLLOUT` event anyway. This is because of router implementation, check _router.cpp_:
```cpp
bool zmq::router_t::xhas_out ()
{
    //  In theory, ROUTER socket is always ready for writing. Whether actual
    //  attempt to write succeeds depends on whitch pipe the message is going
    //  to be routed to.
    return true;
}
```
I'm almost sure this is not a ZMQ bug. So IMO this should be fixed in AZMQ.

**Comment by rodgert** [comment]
Ah, ok. Agreed, I will look at what is required to address this.

**Comment by oliora** [comment]
I'm not aware about this part of AZMQ code but looks like AZMQ should ignore `POLLOUT` event unless there is a blocked async_write operation. This solution is applicable (and even more, required) to all types of sockets.
I'll try to understand existing code and fix it.

**Comment by oliora** [comment]
It was closed  by mistake :)

**Comment by oliora** [comment]
The same problem occurs if pair socket is used, but we need two sockets:
```cpp
#include <boost/asio.hpp>
#include <azmq/socket.hpp>

int main()
{
    boost::asio::io_service ios;

    azmq::pair_socket s1(ios);
    s1.connect("inproc://#1");
    
    azmq::pair_socket s(ios);
    s.bind("inproc://#1");

    s.async_receive([](const boost::system::error_code & ec, azmq::message & msg, size_t bytes_transferred) {
    });

    ios.run();

    return 0;
}
```

**Comment by oliora** [comment]
As status update: I'm deeply working on this issue. After digging into I faced the following ZeroMQ behavior: "The returned file descriptor is also used internally by the zmq_send and zmq_recv functions. As the descriptor is edge triggered, applications must update the state of ZMQ_EVENTS after each invocation of zmq_send or zmq_recv.To be more explicit: after calling zmq_send the socket may become readable (and vice versa) without triggering a read event on the file descriptor."(http://api.zeromq.org/4-2:zmq-getsockopt, ZMQ_FD)
So far it looks like a such behavior ruins AZMQ async operation state machine. Socket just stops receiving with async_receive. @rodgert what do you thing about this?

**Comment by rodgert** [comment]
The behavior that was originally there was based on my reading of that
specific note (and, obviously it is not quite correct). I may get some time
tomorrow to look into this a bit more, and hopefully have a better idea as
to how to address the issue afterwards.

**Comment by oliora** [comment]
Fixed.
@rodgert if you mind some extra work required, please reopen the issue.

**Comment by oliora** [comment]
@rodgert could you please review changes I made and close the issue if they are OK and sufficient to fix the problem?

**Comment by rodgert** [comment]
I've reviewed them and am fine with the changes, thanks!
