### ISSUE TITLE
CURVE_SERVERKEY option is not defined

### ISSUE THREAD

**Issue by kleunen** [zeromq/azmq#90]
In socket.hpp the option ZMQ_CURVE_SERVERKEY is not defined, it should be defined as follows:
    
using curve_publickey = opt::binary < ZMQ_CURVE_PUBLICKEY >;
using curve_privatekey = opt::binary < ZMQ_CURVE_SECRETKEY >;
using curve_serverkey = opt::binary < ZMQ_CURVE_SERVERKEY >;

Otherwise the curve security can not be used with zeromq. With this define, curve security is working

**Comment by xaqq** [comment]
Should be fixed via #95 .
